#!/bin/sh

# Copyright (C) 2012-2015 Jiri Pirko <jiri@resnulli.us>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config "${CONFIG}"

source_config

if [ "${DEVICETYPE}" = "TeamPort" ]; then
	# This means that this was called directly, not via ifup-eth
	# so execute ifup-eth now.
	/etc/sysconfig/network-scripts/ifup-eth ${CONFIG} $2
fi

if [ -n "${TEAM_MASTER}" ]; then
	if [ ! -x /usr/bin/teamdctl ]; then
		net_log $"Team support not available: teamdctl not found"
		exit 1
	fi
	/sbin/ip link show ${TEAM_MASTER} > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		net_log $"Team master is not present yet, delaying port device initialization" info
		exit 0
	fi
	/usr/bin/teamdctl ${TEAM_MASTER} port present ${DEVICE} 2> /dev/null
	if [ $? -eq 0 ]; then
		# port is already part of the team, nothing to do
		exit 0
	fi
	/sbin/ip link set dev ${DEVICE} down
	if [ -n "${TEAM_PORT_CONFIG}" ]; then
		/usr/bin/teamdctl ${TEAM_MASTER} port config update ${DEVICE} "${TEAM_PORT_CONFIG}" || exit 1
	fi
	/usr/bin/teamdctl ${TEAM_MASTER} port add ${DEVICE} || exit 1
fi
