.TH TEAMD 8 "2013-04-01" "libteam" "Team daemon"
.SH NAME
teamd \(em team network device control daemon
.SH SYNOPSIS
.B teamd
.B \-k
.RB [ \-p
.IR pid_file ]
.RB [ \-g ]
.br
.B teamd
.B \-e
.RB [ \-p
.IR pid_file ]
.RB [ \-g ]
.br
.B teamd
.BI \-c " config_text"
.RB [ \-p
.IR pid_file ]
.RB [ \-gdrD ]
.br
.B teamd
.BI \-f " config_file"
.RB [ \-p
.IR pid_file ]
.RB [ \-gdrD ]
.br
.B teamd
.BR  \-h | \-V
.SH DESCRIPTION
.PP
teamd is a daemon to control a given team network device, during runtime,
as a puppeteer controls a puppet. It uses libteam to communicate with the
kernel team device instance via Netlink sockets. The behaviour depends on
the selected runner and its configuration. This daemon is part of the
libteam project.
.SH OPTIONS
.TP
.B "\-h, \-\-help"
Print help text to console and exit.
.TP
.B "\-V, \-\-version"
Print version information to console and exit.
.TP
.B "\-d, \-\-daemonize"
Daemonize after startup.
.TP
.B "\-k, \-\-kill"
Kill running daemon instance.
.TP
.B "\-e, \-\-check"
Return 0 if a daemon is already running.
.TP
.BI "\-f " filename ", \-\-config-file " filename
Load the specified configuration file.
.TP
.BI "\-c " text ", \-\-config "text
Use given config string. If this option is present then \-f option will be
ignored.
.TP
.BI "\-p " filename ", \-\-pid-file " filename
Use the specified PID file.
.TP
.B "\-g, \-\-debug"
Turns on debugging messages. Repeating the option increases verbosity.
.TP
.B "\-r, \-\-force-recreate"
Force team device recreation in case it already exists.
.TP
.BI "\-t " devicename ", \-\-team-dev " devicename
Use the specified team device name (overrides "device" key in config).
.TP
.B "\-n, \-\-no-ports"
Start without ports, even if they are listed in config.
.TP
.B "\-D, \-\-dbus-enable"
Enable D-Bus interface.
.TP
.B "\-U, \-\-usock-enable"
Enable UNIX domain socket interface.
.SH SEE ALSO
.BR teamdctl (8),
.BR teamd.conf (5),
.BR teamnl (8)
.SH AUTHOR
.PP
Jiri Pirko is the original author and current maintainer of libteam.
