#!/bin/sh

# Copyright (C) 2012-2015 Jiri Pirko <jiri@resnulli.us>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config "${CONFIG}"

source_config

if [ "${DEVICETYPE}" = "Team" ]; then
	# This means that this was called directly, not via ifdown-eth
	# so execute ifdown-eth now.
	/etc/sysconfig/network-scripts/ifdown-eth ${CONFIG} $2
fi

if [ -n "${TEAM_CONFIG}" ]; then
	if [ ! -x /usr/bin/teamd ]; then
		net_log $"Team support not available: teamd not found"
		exit 1
	fi
	# Bring down all existing port devices now
	for device in $(LANG=C egrep -l "^[[:space:]]*TEAM_MASTER=\"?${DEVICE}\"?" /etc/sysconfig/network-scripts/ifcfg-*) ; do
		is_ignored_file "$device" && continue
		/sbin/ifdown ${device##*/}
	done
	/usr/bin/systemctl stop teamd@${DEVICE}.service --ignore-dependencies || exit 1
fi
