#!/bin/sh

# Copyright (C) 2012-2015 Jiri Pirko <jiri@resnulli.us>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

. /etc/init.d/functions

cd /etc/sysconfig/network-scripts
. ./network-functions

[ -f ../network ] && . ../network

CONFIG=${1}

need_config "${CONFIG}"

source_config

# If the device is a team, create it with teamd, if available.
if [ -n "${TEAM_CONFIG}" ]; then
	if [ ! -x /usr/bin/teamd ]; then
		net_log $"Team support not available: teamd not found"
		exit 1
		fi
	mkdir -p /run/teamd/  || exit 1
	echo "${TEAM_CONFIG}" > /run/teamd/${DEVICE}.conf  || exit 1
	/usr/bin/systemctl start teamd@${DEVICE}.service  || exit 1
	# Bring up all existing port devices now
	for device in $(LANG=C egrep -l "^[[:space:]]*TEAM_MASTER=\"?${DEVICE}\"?" /etc/sysconfig/network-scripts/ifcfg-*) ; do
		is_ignored_file "$device" && continue
		/sbin/ifup ${device##*/}
	done
fi

if [ "${DEVICETYPE}" = "Team" ]; then
	# This means that this was called directly, not via ifup-eth
	# so execute ifup-eth now.
	exec /etc/sysconfig/network-scripts/ifup-eth ${CONFIG} $2
fi
